export const DomainEvents = {
  EventPublished: 'event.published',
  EventCancelled: 'event.cancelled',
  EventFinished: 'event.finished',
  RegistrationCreated: 'registration.created',
  RegistrationConfirmed: 'registration.confirmed',
  RegistrationCancelled: 'registration.cancelled',
  RegistrationWaitlistPromoted: 'registration.waitlist_promoted',
  CheckInPerformed: 'check_in.performed',
  PaymentApproved: 'payment.approved',
  PaymentRejected: 'payment.rejected',
  PaymentRefunded: 'payment.refunded',
  PaymentRecorded: 'payment.recorded',
  RegistrationFullyPaid: 'registration.fully_paid',
  InstallmentOverdue: 'installment.overdue',
  NotificationCreated: 'notification.created',
  PermissionGranted: 'permission.granted',
  PermissionRevoked: 'permission.revoked',
} as const;
