-- Extiende NotificationType con los valores para flujos de Carta Poder,
-- Sucesión de Presidencia y Fase 4 (solicitudes de ingreso, transferencias).

ALTER TYPE "NotificationType" ADD VALUE 'CARTA_PODER_PENDING_SECRETARY';
ALTER TYPE "NotificationType" ADD VALUE 'CARTA_PODER_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'CARTA_PODER_VERIFIED';
ALTER TYPE "NotificationType" ADD VALUE 'CARTA_PODER_REJECTED';

ALTER TYPE "NotificationType" ADD VALUE 'PRESIDENCY_DESIGNATED';
ALTER TYPE "NotificationType" ADD VALUE 'PRESIDENCY_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE 'PRESIDENCY_NO_SUCCESSOR';
ALTER TYPE "NotificationType" ADD VALUE 'PRESIDENCY_TRANSITION';
ALTER TYPE "NotificationType" ADD VALUE 'PRESIDENCY_REVOKED';

ALTER TYPE "NotificationType" ADD VALUE 'MEMBERSHIP_APPLICATION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'MEMBERSHIP_APPLICATION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'MEMBERSHIP_APPLICATION_REJECTED';

ALTER TYPE "NotificationType" ADD VALUE 'TRANSFER_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'TRANSFER_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'TRANSFER_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'TRANSFER_REJECTED';
